version: '3.8'

services:
  kalypso:
    image: ak4marlin/kalypso-symbiotic-data-bridge:latest
    ports:
      - "6005:6005"
    restart: unless-stopped
    volumes:
      - ./kalypso_symbiotic_data_bridge_config.json:/app/kalypso_symbiotic_data_bridge_config.json
      - ./kalypso-symbiotic-data-bridge:/app/kalypso-symbiotic-data-bridge
